### ISSUE TITLE
Decomp/extract do not respect payload data checksum

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/moss-rs#45]
Each payload header in v1 format contains an 8-byte checksum that is currently ignored.

This uses XXH3_64 and is internally stored as `XXH64_canonical_t`. While reading from the payload, an adapter should be used to build the checksum and compare the hashsum.

Alternatively a read-ahead checksum can be implemented when using `mmap` by pushing the entire payload-body into a digest.

**Comment by tarkah** [comment]
This has since been implemented: https://github.com/serpent-os/moss-rs/blob/bb68b260f7a83be86f38179e2139659feee96d56/crates/stone/src/read/mod.rs#L222
