### ISSUE TITLE
Show Git hash in `moss -v` output

### ISSUE THREAD

**Issue by der-eismann** [serpent-os/moss-rs#84]
Right now `moss -v` only prints `0.1.0` as defined in the Cargo.toml. Would be great if it would print some useful info like the Git hash or  build date. Example from a Go tool we build:
```
$ aws-nuke version
version:     v2.20.0
build date:  Wed Nov 30 13:05:49 CET 2022
scm hash:    4643a3b06dc983708010a0bec7964f794899b7b4
environment: sysop@eduard-laser
go version:  go1.19.3
```

**Comment by ermo** [comment]
@tarkah Any chance you could be persuaded to look at this...?
